const translations={
 en:{atelier:"Atelier",gallery:"Gallery",artist:"Artist",vision:"Vision",journal:"Journal",title:"Bashar's Atelier",subtitle:"A sanctuary of paintings, stories, and timeless artistic exploration.",button:"Enter the Collection",collection:"The Collection",story:"Story Behind The Piece",medium:"Medium",year:"Year",home:"Home",exhibition:"Enter Exhibition Room"},
 ar:{atelier:"المرسم",gallery:"المعرض",artist:"الفنان",vision:"الرؤية",journal:"اليوميات الفنية",title:"مرسم بشار",subtitle:"مساحة فنية تحتضن اللوحات والقصص ورحلة البحث عن الجمال عبر الزمن.",button:"ادخل إلى المجموعة الفنية",collection:"المجموعة الفنية",story:"قصة العمل الفني",medium:"الخامة",year:"السنة",home:"الرئيسية",exhibition:"ادخل إلى قاعة العرض"},
 de:{atelier:"Atelier",gallery:"Galerie",artist:"Künstler",vision:"Vision",journal:"Tagebuch",title:"Bashars Atelier",subtitle:"Ein Raum für Gemälde, Geschichten und zeitlose künstlerische Entdeckungen.",button:"Die Sammlung betreten",collection:"Die Sammlung",story:"Geschichte des Werkes",medium:"Medium",year:"Jahr",home:"Startseite",exhibition:"Ausstellungsraum betreten"},
 it:{atelier:"Atelier",gallery:"Galleria",artist:"Artista",vision:"Visione",journal:"Diario",title:"Atelier di Bashar",subtitle:"Uno spazio di dipinti, storie e ricerca artistica senza tempo.",button:"Entra nella collezione",collection:"La Collezione",story:"Storia dell'opera",medium:"Tecnica",year:"Anno",home:"Home",exhibition:"Entra nella sala espositiva"},
 es:{atelier:"Atelier",gallery:"Galería",artist:"Artista",vision:"Visión",journal:"Diario",title:"Atelier de Bashar",subtitle:"Un espacio de pinturas, historias y exploración artística atemporal.",button:"Entrar en la colección",collection:"La Colección",story:"Historia de la obra",medium:"Técnica",year:"Año",home:"Inicio",exhibition:"Entrar en la sala de exposición"},
 fr:{atelier:"Atelier",gallery:"Galerie",artist:"Artiste",vision:"Vision",journal:"Journal",title:"L'Atelier de Bashar",subtitle:"Un espace de peintures, d'histoires et d'exploration artistique intemporelle.",button:"Entrer dans la collection",collection:"La Collection",story:"Histoire de l'œuvre",medium:"Technique",year:"Année",home:"Accueil",exhibition:"Entrer dans la salle d'exposition"},
 ru:{atelier:"Ателье",gallery:"Галерея",artist:"Художник",vision:"Видение",journal:"Дневник",title:"Ателье Башара",subtitle:"Пространство картин, историй и вечного художественного поиска.",button:"Войти в коллекцию",collection:"Коллекция",story:"История произведения",medium:"Техника",year:"Год",home:"Главная",exhibition:"Войти в выставочный зал"},
 zh:{atelier:"工作室",gallery:"画廊",artist:"艺术家",vision:"理念",journal:"日志",title:"巴沙尔的工作室",subtitle:"收藏绘画、故事与永恒艺术探索的空间。",button:"进入收藏",collection:"作品集",story:"作品故事",medium:"媒介",year:"年份",home:"首页",exhibition:"进入展厅"},
 ja:{atelier:"アトリエ",gallery:"ギャラリー",artist:"アーティスト",vision:"理念",journal:"日誌",title:"バシャールのアトリエ",subtitle:"絵画、物語、そして時代を超えた芸術探求の空間。",button:"コレクションへ",collection:"コレクション",story:"作品の物語",medium:"技法",year:"制作年",home:"ホーム",exhibition:"展示室へ"},
 nl:{atelier:"Atelier",gallery:"Galerij",artist:"Kunstenaar",vision:"Visie",journal:"Dagboek",title:"Bashar's Atelier",subtitle:"Een ruimte van schilderijen, verhalen en tijdloze artistieke ontdekkingen.",button:"Betreed de collectie",collection:"De Collectie",story:"Het verhaal achter het werk",medium:"Techniek",year:"Jaar",home:"Home",exhibition:"Betreed de tentoonstellingsruimte"},
 el:{atelier:"Ατελιέ",gallery:"Γκαλερί",artist:"Καλλιτέχνης",vision:"Όραμα",journal:"Ημερολόγιο",title:"Το Ατελιέ του Bashar",subtitle:"Ένας χώρος ζωγραφικών έργων, ιστοριών και διαχρονικής καλλιτεχνικής αναζήτησης.",button:"Είσοδος στη συλλογή",collection:"Η Συλλογή",story:"Ιστορία του έργου",medium:"Τεχνική",year:"Έτος",home:"Αρχική",exhibition:"Είσοδος στην αίθουσα"}
};
function setLanguage(lang){localStorage.setItem('basharLanguage',lang);location.reload();}